name: cp-knowledge-graph
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4
  - flask=2.0.1
  - flask-graphql
  - graphene
  - graphene-mongo
  - mongoengine
  - mongomock
  - python>=3.6
  - pip
  - pip:
      - autoscraper
      - pre-commit
